AWSTemplateFormatVersion: '2010-09-09'
Description: Creates an S3 bucket, Cloudfront to host chrono-lite frontend

Parameters:
  BucketName:
    Type: String
    Description: S3 Bucket Name
    AllowedPattern: "^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$"
    ConstraintDescription: must be a valid S3 Bucket name.
    Default: "tc-chrono-lite"
  FullDomainName:
    Type: String
    Description: The full domain name e.g. chrono-lite.togglecorp.com
    AllowedPattern: (?!-)[a-zA-Z0-9-.]{1,63}(?<!-)
    ConstraintDescription: must be a valid DNS zone name.
    Default: "chrono-lite.togglecorp.com"
  DomainName:
    Type: String
    Description: The domain name e.g. togglecorp.com. Used to send validation domain validation.
    AllowedPattern: (?!-)[a-zA-Z0-9-.]{1,63}(?<!-)
    ConstraintDescription: must be a valid DNS zone name.
    Default: "togglecorp.com"
  CertificateAuthorityArn:
    Type: String
    Description: the Amazon Resource Name (ARN) of an AWS Certificate Manager (ACM) certificate.
    AllowedPattern: "^$|arn:aws:acm:.*"
    Default: ""

Conditions:
  NoExistingCertificateAuthorityArn: !Equals [!Ref CertificateAuthorityArn, ""]

Resources:
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref 'BucketName'
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
    DeletionPolicy: Retain

  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref 'WebsiteBucket'
      PolicyDocument:
        Statement:
        - Sid: PublicReadForGetBucketObjects
          Effect: Allow
          Principal: '*'
          Action: s3:GetObject
          Resource: !Join ['', ['arn:aws:s3:::', !Ref 'WebsiteBucket', /*]]

  AcmCertificate:
    Type: AWS::CertificateManager::Certificate
    Condition: NoExistingCertificateAuthorityArn
    Properties:
      CertificateTransparencyLoggingPreference: 'DISABLED'
      DomainName: !Ref 'FullDomainName'
      ValidationMethod: 'EMAIL'
      ValidationDomain: !Ref 'DomainName'
      Tags:
        Name: Chrono-lite

  WebsiteCloudfront:
    Type: AWS::CloudFront::Distribution
    DependsOn:
    - WebsiteBucket
    Properties:
      DistributionConfig:
        Comment: Cloudfront Distribution pointing to S3 bucket
        Origins:
        - DomainName: !Select [2, !Split ["/", !GetAtt WebsiteBucket.WebsiteURL]]
          Id: S3Origin
          CustomOriginConfig:
            HTTPPort: '80'
            HTTPSPort: '443'
            OriginProtocolPolicy: http-only
        Enabled: true
        HttpVersion: 'http2'
        DefaultRootObject: index.html
        Aliases:
        - !Ref 'FullDomainName'
        DefaultCacheBehavior:
          AllowedMethods:
          - GET
          - HEAD
          Compress: true
          TargetOriginId: S3Origin
          ForwardedValues:
            QueryString: true
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https
        PriceClass: PriceClass_All
        ViewerCertificate:
          AcmCertificateArn: !If [NoExistingCertificateAuthorityArn, !Ref AcmCertificate, !Ref CertificateAuthorityArn]
          SslSupportMethod: sni-only

  ClientUpdateIamPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: 'chrono-lite-update-policy'
      Description: Policy for to update static files and invalidate CloudFront cache
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - cloudfront:CreateInvalidation
            Effect: Allow
            Resource:
              - !Join ['', [!Sub 'arn:aws:cloudfront::${AWS::AccountId}:distribution/', !Ref 'WebsiteCloudfront']]
          - Action:
              - s3:DeleteObject
              - s3:GetBucketLocation
              - s3:GetObject
              - s3:ListBucket
              - s3:PutObject
              - s3:PutObjectAcl
            Effect: Allow
            Resource:
              - !Join ['', ['arn:aws:s3:::', !Ref 'WebsiteBucket']]
              - !Join ['', ['arn:aws:s3:::', !Ref 'WebsiteBucket', /*]]

Outputs:
  BucketName:
    Value: !Ref 'WebsiteBucket'
    Description: Name of S3 bucket to hold website content
  CloudfrontEndpoint:
    Value: !GetAtt [WebsiteCloudfront, DomainName]
    Description: Endpoint for Cloudfront distribution
  FullDomain:
    Value: !Ref 'FullDomainName'
    Description: Full DomainName
